import { pose } from './pose'
import {
  CEILING_CRAWL_DROP_ANCHOR,
  CEILING_CRAWL_LOW_ANCHOR,
  CEILING_CRAWL_RECOVER_ANCHOR,
  CEILING_CRAWL_STRETCH_ANCHOR,
  CEILING_GRAB_ANCHOR,
  DASH_BODY_ANCHOR,
  GROUND_FOOT_ANCHOR,
  PULL_OUT_BODY_ANCHOR,
  RUN_BODY_ANCHOR,
  WALL_GRAB_ANCHOR,
} from './anchors'

// These are the original Chibiterasu Shimeji action poses from actions.xml.
// The Java runtime moves left by default and flips the sprite when it looks right.
export const SHIMEJI_ACTIONS = {
  stand: {
    label: '立つ',
    frame: 'ground',
    loop: true,
    poses: [pose('shime1')],
  },
  walk: {
    label: '歩く',
    frame: 'ground',
    loop: true,
    poses: [
      pose('shime1', GROUND_FOOT_ANCHOR, [-2, 0], 6),
      pose('shime2', GROUND_FOOT_ANCHOR, [-2, 0], 6),
      pose('shime1', GROUND_FOOT_ANCHOR, [-2, 0], 6),
      pose('shime3', GROUND_FOOT_ANCHOR, [-2, 0], 6),
    ],
  },
  run: {
    label: '走る',
    frame: 'ground',
    loop: true,
    poses: [
      pose('shime47', RUN_BODY_ANCHOR, [-4, 0], 5),
      pose('shime48', GROUND_FOOT_ANCHOR, [-4, 0], 3),
      pose('shime49', GROUND_FOOT_ANCHOR, [-4, 0], 3),
    ],
  },
  dash: {
    label: '猛ダッシュ',
    frame: 'ground',
    loop: true,
    poses: [
      pose('shime47', DASH_BODY_ANCHOR, [-8, 0], 5),
      pose('shime48', GROUND_FOOT_ANCHOR, [-8, 0], 3),
      pose('shime49', GROUND_FOOT_ANCHOR, [-8, 0], 3),
    ],
  },
  sit: {
    label: '座る',
    frame: 'ground',
    loop: true,
    poses: [pose('shime11')],
  },
  relaxedSit: {
    label: '楽に座る',
    frame: 'ground',
    loop: true,
    poses: [pose('shime30')],
  },
  sitFeetDown: {
    label: '足を下ろして座る',
    frame: 'ground',
    loop: true,
    poses: [pose('shime31')],
  },
  dangleFeet: {
    label: '足をぶらぶらさせる',
    frame: 'ground',
    loop: true,
    poses: [
      pose('shime51', GROUND_FOOT_ANCHOR, [0, 0], 25),
      pose('shime32', GROUND_FOOT_ANCHOR, [0, 0], 25),
      pose('shime51', GROUND_FOOT_ANCHOR, [0, 0], 25),
      pose('shime33', GROUND_FOOT_ANCHOR, [0, 0], 25),
    ],
  },
  lookUp: {
    label: '座って見上げる',
    frame: 'ground',
    loop: true,
    poses: [pose('shime26')],
  },
  lie: {
    label: '寝そべる',
    frame: 'ground',
    loop: true,
    poses: [pose('shime50')],
  },
  crawl: {
    label: 'ずりずり',
    frame: 'ground',
    loop: true,
    poses: [
      pose('shime20', GROUND_FOOT_ANCHOR, [0, 0], 28),
      pose('shime20', GROUND_FOOT_ANCHOR, [-2, 0], 4),
      pose('shime21', GROUND_FOOT_ANCHOR, [-2, 0], 4),
      pose('shime21', GROUND_FOOT_ANCHOR, [-1, 0], 4),
      pose('shime21', GROUND_FOOT_ANCHOR, [0, 0], 24),
    ],
  },
  jump: {
    label: 'ジャンプ',
    frame: 'air',
    loop: true,
    poses: [pose('shime22')],
  },
  fall: {
    label: '落ちる',
    frame: 'air',
    loop: true,
    poses: [pose('shime4')],
  },
  bounce: {
    label: '跳ねる',
    frame: 'ground',
    loop: true,
    poses: [
      pose('shime18', GROUND_FOOT_ANCHOR, [0, 0], 4),
      pose('shime19', GROUND_FOOT_ANCHOR, [0, 0], 4),
    ],
  },
  holdWall: {
    label: '壁に掴まる',
    frame: 'wall',
    loop: true,
    poses: [pose('shime63', WALL_GRAB_ANCHOR, [0, 0], 250)],
  },
  climbWallUp: {
    label: '壁を登る',
    frame: 'wall',
    loop: true,
    poses: [
      pose('shime14', WALL_GRAB_ANCHOR, [0, 0], 16),
      pose('shime14', WALL_GRAB_ANCHOR, [0, -1], 4),
      pose('shime12', WALL_GRAB_ANCHOR, [0, -1], 4),
      pose('shime13', WALL_GRAB_ANCHOR, [0, -1], 4),
      pose('shime13', WALL_GRAB_ANCHOR, [0, 0], 16),
      pose('shime13', WALL_GRAB_ANCHOR, [0, -2], 4),
      pose('shime12', WALL_GRAB_ANCHOR, [0, -2], 4),
      pose('shime14', WALL_GRAB_ANCHOR, [0, -2], 4),
    ],
  },
  climbWallDown: {
    label: '壁を降りる',
    frame: 'wall',
    loop: true,
    poses: [
      pose('shime14', WALL_GRAB_ANCHOR, [0, 0], 16),
      pose('shime14', WALL_GRAB_ANCHOR, [0, 2], 4),
      pose('shime12', WALL_GRAB_ANCHOR, [0, 2], 4),
      pose('shime13', WALL_GRAB_ANCHOR, [0, 2], 4),
      pose('shime13', WALL_GRAB_ANCHOR, [0, 0], 16),
      pose('shime13', WALL_GRAB_ANCHOR, [0, 1], 4),
      pose('shime12', WALL_GRAB_ANCHOR, [0, 1], 4),
      pose('shime14', WALL_GRAB_ANCHOR, [0, 1], 4),
    ],
  },
  holdCeiling: {
    label: '天井に掴まる',
    frame: 'ceiling',
    loop: true,
    poses: [pose('shime65', CEILING_GRAB_ANCHOR, [0, 0], 250)],
  },
  crawlCeiling: {
    label: '天井を伝う',
    frame: 'ceiling',
    loop: true,
    poses: [
      pose('shime23', CEILING_GRAB_ANCHOR, [0, 0], 16),
      pose('shime24', CEILING_GRAB_ANCHOR, [0, 0], 4),
      pose('shime25', CEILING_CRAWL_DROP_ANCHOR, [-11, 0], 1),
      pose('shime25', CEILING_CRAWL_LOW_ANCHOR, [-10, 0], 2),
      pose('shime25', CEILING_CRAWL_STRETCH_ANCHOR, [-9, 0], 4),
      pose('shime25', CEILING_CRAWL_LOW_ANCHOR, [-8, 0], 3),
      pose('shime25', CEILING_CRAWL_RECOVER_ANCHOR, [-7, 0], 2),
      pose('shime64', CEILING_GRAB_ANCHOR, [0, 0], 5),
      pose('shime23', CEILING_GRAB_ANCHOR, [0, 0], 4),
    ],
  },
  drag: {
    label: 'つままれる',
    frame: 'air',
    loop: true,
    poses: [
      pose('shime9', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime7', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime59', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime8', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime10', GROUND_FOOT_ANCHOR, [0, 0], 5),
    ],
  },
  resist: {
    label: '抵抗する',
    frame: 'air',
    loop: true,
    poses: [
      pose('shime5', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime6', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime5', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime6', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime59', GROUND_FOOT_ANCHOR, [0, 0], 50),
    ],
  },
  pullOut: {
    label: '引っこ抜く1',
    frame: 'ground',
    loop: false,
    poses: [
      pose('shime1', GROUND_FOOT_ANCHOR, [0, 0], 16),
      pose('shime38', PULL_OUT_BODY_ANCHOR, [0, 0], 30),
      pose('shime39', PULL_OUT_BODY_ANCHOR, [0, 0], 20),
      pose('shime40', PULL_OUT_BODY_ANCHOR, [0, 0], 20),
      pose('shime39', PULL_OUT_BODY_ANCHOR, [0, 0], 10),
      pose('shime40', PULL_OUT_BODY_ANCHOR, [0, 0], 10),
      pose('shime41', PULL_OUT_BODY_ANCHOR, [0, 0], 40),
    ],
  },
  split: {
    label: '分裂1',
    frame: 'ground',
    loop: false,
    poses: [
      pose('shime42', GROUND_FOOT_ANCHOR, [0, 0], 20),
      pose('shime43', GROUND_FOOT_ANCHOR, [0, 0], 10),
      pose('shime44', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime45', GROUND_FOOT_ANCHOR, [0, 0], 15),
      pose('shime46', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime52', GROUND_FOOT_ANCHOR, [0, 0], 15),
      pose('shime53', GROUND_FOOT_ANCHOR, [0, 0], 7),
      pose('shime54', GROUND_FOOT_ANCHOR, [0, 0], 5),
      pose('shime55', GROUND_FOOT_ANCHOR, [0, 0], 15),
      pose('shime56', GROUND_FOOT_ANCHOR, [0, 0], 15),
      pose('shime57', GROUND_FOOT_ANCHOR, [0, 0], 10),
      pose('shime58', GROUND_FOOT_ANCHOR, [0, 0], 30),
    ],
  },
}
